//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_Vendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int Id { get; set; }
        public int Fornecedor_Id { get; set; }
        public int Cliente_Id { get; set; }
        public int Material_Id { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
    }
}
